language: minimal

dist: xenial



env:
  - OXID=6.1
  - OXID=6.0

cache:
  directories:
  - $HOME/OXID
services: 
 - docker

before_instal
  - echo 'Europe/Berlin' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata

before_script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - docker swarm init
  - docker stack deploy --compose-file docker-compose.yml oxid
  - docker run --network=oxid_proxy -ti keywanghadamioxid/php-apache-full:7.1 bash ../build.sh
#  - mysql -e 'CREATE DATABASE oxid;'
#  - sh ./build.sh

script:
  - cd ~/OXID/
#  - ./vendor/bin/runtests-coverage
  - ./vendor/bin/runtests
#  - php vendor/bin/codacycoverage clover ~/OXID/source/modules/oxcom/moduleinternals/Tests/reports/clover.xml --git-commit=$TRAVIS_COMMIT

before_cache:
#  - composer remove "oxid-community/moduleinternals"
#  - rm -rf ~/OXID/source/modules/oxcom/moduleinternals
#  - rm -rf ~/OXID/vendor/oxid-community/moduleinternals
#  - rm -rf ~/OXID/source/tmp/*

