language: minimal
dist: xenial
env:
  - OXID=6.1
#  - OXID=6.0
#cache:
#  directories:
#  - $HOME/OXID
services:
  - docker
before_install:
  - echo 'Europe/Berlin' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - docker node ls
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
before_script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - bash ./ci/prepare.sh
script:
  - bash ./ci/execOnFpm bash /var/www/test.sh
before_cache:
#  - composer remove "oxid-community/moduleinternals"
#  - rm -rf ~/OXID/source/modules/oxcom/moduleinternals
#  - rm -rf ~/OXID/vendor/oxid-community/moduleinternals
#  - rm -rf ~/OXID/source/tmp/*
