version: '3.7'
services:

  selenium:
    image: selenium/standalone-chrome
    networks:
      - proxy
    ports:
      - 4444:4444

  fpm:
    image: keywanghadamioxid/php-fpm-oxid
    networks:
      - proxy
    volumes:
      - ${PWD}/:/module
  apache:
    image: httpd:2.4-alpine
    hostname: oxid.local
    depends_on:
      - mysql
      - fpm
    volumes:
      - ${PWD}/:/module
    ports:
      - 8080:80
    networks:
      - proxy
      
  mysql:
    image: mysql:5.7
    hostname: mysql
    environment:
      MYSQL_DATABASE: oxid
      MYSQL_USER: oxid
      MYSQL_PASSWORD: oxid
      MYSQL_ROOT_PASSWORD: oxid
    networks:
      - proxy

networks:
  proxy:
    driver: overlay
    attachable: true
